import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '../components/Header/Header'
import Block from '../components/Block/Block'
import styles from '../styles/Home.module.css'
import Footer from '../components/Footer/Footer'
import Contacts from '../components/Contacts/Contacts'
import Partheners from '../components/Partheners/Partheners'
import Map from '../components/Map/Map'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Продажа угля</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id='top-section'></div>
      <Header />
      <Block />
      <div id='map-section'></div>
      <Map />
      <div id='contacts-section'></div>
      <Contacts />
      <div id='partheners-section'></div>
      <h3>Партнеры программы</h3>
      <Partheners />
      <Partheners />
      <Partheners />
      <Footer />
    </div>
  )
}
